# Generated by Django 4.1.2 on 2022-10-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('py_sns_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slag',
            new_name='slug',
        ),
    ]
