# Generated by Django 4.1.2 on 2022-10-20 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('py_sns_app', '0002_rename_slag_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted_date',
            new_name='created_at',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='py_sns_app.post')),
            ],
        ),
    ]
